language: ruby
cache: bundler
rvm:
  - 2.1.1
branches:
  only:
    - master
    - /^release\/.*$/
    - /^hotfix\/.*$/
    - /^feature\/.*$/
    - /^bug\/.*$/
    - /^chore\/.*$/
bundler_args: --without development
